### ISSUE TITLE
Fail to make

### ISSUE THREAD

**Issue by tadam98** [PINTO0309/wsl2_linux_kernel_usbcam_enable_conf#1]
When runing them make I get the following error. See attached .config uploaded as **dot.config.txt**
```
drivers/hv/dxgkrnl/dxgmodule.c:392:39: error: initializer element is not constant
 const int DXGK_VMBUS_VERSION_OFFSET = DXGK_VMBUS_CHANNEL_ID_OFFSET +
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/hv/dxgkrnl/dxgmodule.c:395:41: error: initializer element is not constant
 const int DXGK_VMBUS_VGPU_LUID_OFFSET = DXGK_VMBUS_VERSION_OFFSET +
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/hv/dxgkrnl/dxgmodule.c:398:41: error: initializer element is not constant
 const int DXGK_VMBUS_GUESTCAPS_OFFSET = DXGK_VMBUS_VERSION_OFFSET +
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
scripts/Makefile.build:280: recipe for target 'drivers/hv/dxgkrnl/dxgmodule.o' failed
make[3]: *** [drivers/hv/dxgkrnl/dxgmodule.o] Error 1
scripts/Makefile.build:497: recipe for target 'drivers/hv/dxgkrnl' failed
make[2]: *** [drivers/hv/dxgkrnl] Error 2
scripts/Makefile.build:497: recipe for target 'drivers/hv' failed
make[1]: *** [drivers/hv] Error 2
Makefile:1822: recipe for target 'drivers' failed
make: *** [drivers] Error 2
```
[dot.config.txt](https://github.com/PINTO0309/wsl2_linux_kernel_usbcam_enable_conf/files/7359639/dot.config.txt)

**Note**: this error also happens when compiling with the **original** config taken from /proc/config.gz

**Comment by PINTO0309** [comment]
Your question is not fair. First, you should write information about the environment you are using. You should then run a diff of the config to see the differences in content. The environment in which I generated the config is WSL2 Ubuntu20.04. The GCC versions are completely different.
![Screenshot 2021-10-17 20:18:34](https://user-images.githubusercontent.com/33194443/137625146-e3dd1e9b-41d2-416d-84d6-ced022a72106.png)

**Use `sudo make menuconfig`** to generate the config yourself.

**Comment by PINTO0309** [comment]
It's almost the same setup procedure. However, not all the same settings are valid, so you need to refer only to the necessary items.
https://zenn.dev/pinto0309/articles/c3014043502245#4-4.-building-the-linux-kernel

**Comment by tadam98** [comment]
Hi,

I built a new config and it does not pass the make.
I checked with the original config from /proc/config.gz and I get the same error.
So I opened a ticket with Microsoft https://github.com/microsoft/WSL/issues/7558 .

Thank you so much for providing the procedure.

Best,
Mickey

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by tadam98** [comment]
Executing the usbcam_test.py I am getting partial images that look like this:
![test](https://user-images.githubusercontent.com/21152079/139597192-98f30842-ec27-4e16-a7b1-33c7fcd07f3c.jpg)
I tried:
// https://answers.opencv.org/question/120525/opencv-select-timeout-at-high-resolutions/ 
```
$ sudo chmod 777 /dev/vid*
$ fswebcam -r 640x480 --jpeg 95 -D 1 test.jpg
$ sudo rmmod uvcvideo
$ sudo modprobe uvcvideo quirks=128 nodrop=1 timeout=6000
$ fswebcam -r 640x480 --jpeg 95 -D 1 test.jpg
```

**Comment by tadam98** [comment]
I checked with flexihub demo and all my webcams worked **perfectly** on WSL2 18.04/win10 kernel rebuilt with usbip and v4l support. The problems are with VirtualHere. The instrructions in your publication are perfect for your evironment and very inpiring for other environments.

Thanks you.

**Comment by tadam98** [comment]
Support of virtualhere arrived to conclusion that usbip of 18.04 has a problem.
https://virtualhere.com/content/wsl2-client-execution-fails-vhci-hcd-not-found

It explains how it works well with Ubuntu 20.04 and not in my installations.
Best,
Mickey

**Comment by PINTO0309** [comment]
To connect a USB device to WSL 2 and access the USB device from a Linux distribution
https://kledgeb.blogspot.com/2021/11/wsl-227-wsl-2usblinuxusb.html

**Comment by tadam98** [comment]
Hi,

Does it also work for Ubuntu 18.04 ?

Best,
Mickey
________________________________
