### ISSUE TITLE
error in make -j$(nproc)

### ISSUE THREAD

**Issue by ddrigass** [PINTO0309/wsl2_linux_kernel_usbcam_enable_conf#2]
Hi! Thank you for making a huge contribution to improve the WSL. I tried to repeat all the steps according to your instructions, but I had a problem at this stage:

```
$ sudo make -j$(nproc) && \
sudo make modules_install -j$(nproc) && \
sudo make install -j$(nproc)
```

Attached error [logs.txt](https://github.com/PINTO0309/wsl2_linux_kernel_usbcam_enable_conf/files/8089356/logs.txt)

```
Error!  The /var/lib/dkms/ndiswrapper/1.60/5.10.60.1-microsoft-standard-WSL2+/x86_64/dkms.conf for module ndiswrapper includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
```

**Comment by PINTO0309** [comment]
Since only a partial log is pasted, nothing can be determined.

**Comment by ddrigass** [comment]
> Since only a partial log is pasted, nothing can be determined.

[screenlog.0.txt](https://github.com/PINTO0309/wsl2_linux_kernel_usbcam_enable_conf/files/8095528/screenlog.0.txt)

**Comment by PINTO0309** [comment]
What do you see when you run the following?
```bash
$ cat /etc/issue
```

**Comment by PINTO0309** [comment]
There has been no progress, so it is closed.
